"""
Briefer — synthesizes accumulated forge artifacts into a structured morning briefing.

Reads all forge-output/ files and produces:
  - Executive summary
  - Key findings by category
  - Priority items
  - Recommendations
  - Statistics

Outputs markdown (default) and optional HTML.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any

import json

from jinja2 import Template

from .models import OllamaClient

logger = logging.getLogger("slackwater_forge")


# HTML template for briefing output
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>🌅 Morning Briefing — {{ date }}</title>
<style>
  :root {
    --bg: #0d1117;
    --card: #161b22;
    --border: #30363d;
    --text: #c9d1d9;
    --heading: #f0f6fc;
    --accent: #58a6ff;
    --green: #3fb950;
    --yellow: #d29922;
    --red: #f85149;
    --muted: #8b949e;
  }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
    background: var(--bg);
    color: var(--text);
    max-width: 900px;
    margin: 0 auto;
    padding: 24px 16px;
    line-height: 1.6;
  }
  h1 { color: var(--heading); border-bottom: 1px solid var(--border); padding-bottom: 12px; }
  h2 { color: var(--accent); margin-top: 32px; }
  h3 { color: var(--heading); }
  .header-bar {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    flex-wrap: wrap;
    gap: 8px;
  }
  .meta { color: var(--muted); font-size: 0.9em; }
  .stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 12px;
    margin: 20px 0;
  }
  .stat-card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 16px;
    text-align: center;
  }
  .stat-value { font-size: 2em; font-weight: 700; color: var(--heading); }
  .stat-label { color: var(--muted); font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.05em; }
  .priority-high { border-left: 4px solid var(--red); }
  .priority-medium { border-left: 4px solid var(--yellow); }
  .priority-low { border-left: 4px solid var(--green); }
  .artifact-card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 12px;
  }
  .artifact-card .title { color: var(--heading); font-weight: 600; }
  .artifact-card .badge {
    display: inline-block;
    font-size: 0.75em;
    padding: 2px 8px;
    border-radius: 12px;
    background: var(--border);
    margin-left: 8px;
  }
  pre {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 12px;
    overflow-x: auto;
  }
  .confidence {
    display: inline-block;
    padding: 4px 12px;
    border-radius: 4px;
    font-weight: 600;
  }
  .confidence-high { background: rgba(63, 185, 80, 0.2); color: var(--green); }
  .confidence-medium { background: rgba(210, 153, 34, 0.2); color: var(--yellow); }
  .confidence-low { background: rgba(248, 81, 73, 0.2); color: var(--red); }
</style>
</head>
<body>
<div class="header-bar">
  <h1>🌅 Morning Briefing</h1>
  <span class="meta">{{ date }}</span>
</div>
<p class="meta">Generated by Slackwater Forge · {{ generated_at }}</p>

<div class="stats-grid">
  <div class="stat-card"><div class="stat-value">{{ artifacts|length }}</div><div class="stat-label">Artifacts</div></div>
  <div class="stat-card"><div class="stat-value">{{ models|length }}</div><div class="stat-label">Models</div></div>
  <div class="stat-card"><div class="stat-value">{{ total_tokens }}</div><div class="stat-label">Tokens</div></div>
  <div class="stat-card"><div class="stat-value">{{ stats.hours if stats.hours else '—' }}</div><div class="stat-label">GPU Hours</div></div>
  <div class="stat-card"><div class="stat-value">$0.00</div><div class="stat-label">Cost</div></div>
</div>

{% if summary %}
<h2>📋 Executive Summary</h2>
{{ summary }}
{% endif %}

{% if priority_items %}
<h2>🔥 Priority Items</h2>
{% for item in priority_items %}
<div class="artifact-card {{ 'priority-' + item.priority if item.priority else '' }}">
  <span class="title">{{ item.job_name }}</span>
  <span class="badge">{{ item.priority|upper }}</span>
  <p class="meta">{{ item.preview }}</p>
</div>
{% endfor %}
{% endif %}

<h2>📦 All Artifacts ({{ artifacts|length }})</h2>
{% for a in artifacts %}
<div class="artifact-card {{ 'priority-' + a.priority if a.priority else '' }}">
  <span class="title">{{ a.job_name }}</span>
  <span class="badge">{{ a.job_type }}</span>
  <span class="badge">{{ a.model }}</span>
  <p class="meta">{{ a.tokens_generated }} tokens · {{ a.elapsed_seconds }}s · {{ a.timestamp }}</p>
  <details><summary>Preview</summary><pre>{{ a.preview }}</pre></details>
</div>
{% endfor %}

{% if recommendations %}
<h2>🎯 Recommendations</h2>
<ol>
{% for rec in recommendations %}
  <li>{{ rec }}</li>
{% endfor %}
</ol>
{% endif %}

<p class="meta">Confidence: {{ confidence_pct }}% · {{ artifacts|length }} artifacts analyzed</p>
</body>
</html>"""


def _extract_preview(text: str, max_chars: int = 300) -> str:
    """Extract a clean preview from artifact text."""
    if not text:
        return ""
    # Strip code blocks for preview
    cleaned = re.sub(r"```[\s\S]*?```", "[code block]", text)
    cleaned = re.sub(r"^#{1,6}\s+", "", cleaned, flags=re.MULTILINE)
    lines = [l.strip() for l in cleaned.split("\n") if l.strip()]
    preview = " ".join(lines)[:max_chars]
    return preview + ("..." if len(cleaned) > max_chars else "")


def _categorize(artifacts: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Group artifacts by job_type."""
    categories: dict[str, list[dict[str, Any]]] = {}
    for a in artifacts:
        cat = a.get("job_type", "other")
        categories.setdefault(cat, []).append(a)
    return categories


def _compute_confidence(artifacts: list[dict[str, Any]]) -> float:
    """
    Estimate briefing confidence.
    Based on artifact count and cross-references.
    """
    if not artifacts:
        return 0.0
    base = min(len(artifacts) / 10.0, 1.0)  # More artifacts = more confidence
    # Bonus for diverse types
    types = set(a.get("job_type", "") for a in artifacts)
    diversity_bonus = min(len(types) * 0.05, 0.2)
    # Bonus for verified artifacts
    verified = sum(1 for a in artifacts if a.get("verified", False))
    verify_bonus = min(verified * 0.1, 0.2)
    return min(base + diversity_bonus + verify_bonus, 1.0)


class Briefer:
    """
    Synthesizes forge artifacts into morning briefings.

    Can optionally use Ollama to generate a summary, or work purely
    from artifact metadata (offline mode).
    """

    def __init__(
        self,
        output_dir: str | Path = "forge-output",
        ollama_host: str = "localhost",
        ollama_port: int = 11434,
    ) -> None:
        self.output_dir = Path(output_dir)
        self.client = OllamaClient(host=ollama_host, port=ollama_port)

    def load_artifacts(self) -> list[dict[str, Any]]:
        """Load all artifact metadata from the output directory."""
        artifacts = []
        for f in sorted(self.output_dir.glob("*.json")):
            if f.name.startswith("."):
                continue
            try:
                data = json.loads(f.read_text())  # type: ignore (json imported in forge.py scope)
            except (json.JSONDecodeError, IOError):
                continue

            # Also load the markdown text if available
            md_path = f.with_suffix(".md")
            if md_path.exists():
                data["full_text"] = md_path.read_text()
            else:
                data["full_text"] = data.get("text", "")

            data["preview"] = _extract_preview(data.get("text", ""))
            artifacts.append(data)
        return artifacts

    def generate(
        self,
        model: str | None = None,
        recipient: str = "Operator",
        use_ai_summary: bool = True,
    ) -> dict[str, Any]:
        """
        Generate a structured briefing from accumulated artifacts.

        Args:
            model: Ollama model to use for AI summarization (None = offline mode).
            recipient: Name of the briefing recipient.
            use_ai_summary: If True and model is set, use Ollama for summary.

        Returns:
            Briefing data dict with all sections.
        """
        artifacts = self.load_artifacts()
        if not artifacts:
            return {
                "date": datetime.now().strftime("%Y-%m-%d"),
                "generated_at": datetime.now().isoformat(),
                "recipient": recipient,
                "error": "No artifacts found in output directory",
                "artifacts": [],
            }

        categories = _categorize(artifacts)
        confidence = _compute_confidence(artifacts)
        total_tokens = sum(a.get("tokens_generated", 0) for a in artifacts)
        models_used = sorted(set(a.get("model", "") for a in artifacts if a.get("model")))

        # Priority items (high/critical first)
        priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        priority_items = sorted(
            [a for a in artifacts if a.get("priority") in priority_order],
            key=lambda a: priority_order.get(a.get("priority", "low"), 99),
        )

        # AI-generated executive summary (optional)
        summary = ""
        recommendations: list[str] = []
        if use_ai_summary and model and self.client.is_available():
            summary, recommendations = self._ai_synthesize(artifacts, model)
        else:
            summary = self._offline_summary(artifacts, categories)

        briefing = {
            "date": datetime.now().strftime("%Y-%m-%d"),
            "generated_at": datetime.now().isoformat(),
            "recipient": recipient,
            "summary": summary,
            "priority_items": priority_items,
            "artifacts": artifacts,
            "models": models_used,
            "total_tokens": total_tokens,
            "confidence": confidence,
            "confidence_pct": round(confidence * 100),
            "recommendations": recommendations,
            "categories": {k: len(v) for k, v in categories.items()},
            "stats": {
                "total": len(artifacts),
                "hours": round(
                    sum(a.get("elapsed_seconds", 0) for a in artifacts) / 3600, 1
                ),
            },
        }
        return briefing

    def _ai_synthesize(
        self, artifacts: list[dict[str, Any]], model: str
    ) -> tuple[str, list[str]]:
        """Use Ollama to generate an executive summary and recommendations."""
        # Prepare a condensed view for the model
        previews = []
        for a in artifacts[:20]:  # Limit to avoid token overflow
            previews.append(
                f"- [{a.get('job_type', '?')}] {a.get('job_name', '?')}: "
                f"{a.get('preview', '')[:150]}"
            )
        artifact_list = "\n".join(previews)

        prompt = f"""Analyze these overnight forge artifacts and provide:

1. A concise executive summary (2-3 paragraphs)
2. 3-5 actionable recommendations based on the artifacts

Artifacts produced overnight:
{artifact_list}

Format your response as:

## Executive Summary
[summary text]

## Recommendations
1. [rec 1]
2. [rec 2]
..."""

        try:
            result = self.client.generate(
                model=model,
                prompt=prompt,
                system="You are a morning briefing analyst. Be concise, specific, and actionable.",
            )
            text = result.text

            # Parse sections
            summary = ""
            recommendations: list[str] = []

            if "## Executive Summary" in text:
                parts = text.split("## Executive Summary", 1)
                rest = parts[1] if len(parts) > 1 else text
                if "## Recommendations" in rest:
                    sum_part, rec_part = rest.split("## Recommendations", 1)
                    summary = sum_part.strip()
                    for line in rec_part.strip().split("\n"):
                        line = line.strip()
                        if line and line[0].isdigit():
                            # Remove leading number
                            cleaned = re.sub(r"^\d+\.\s*", "", line)
                            if cleaned:
                                recommendations.append(cleaned)
                else:
                    summary = rest.strip()
            else:
                summary = text.strip()

            return summary, recommendations
        except Exception as e:
            logger.warning("AI synthesis failed: %s, falling back to offline", e)
            return self._offline_summary(artifacts, _categorize(artifacts)), []

    def _offline_summary(
        self,
        artifacts: list[dict[str, Any]],
        categories: dict[str, list[dict[str, Any]]],
    ) -> str:
        """Generate a basic summary without AI (metadata-only mode)."""
        lines = [
            f"Overnight forge produced {len(artifacts)} artifacts "
            f"across {len(categories)} categories.",
            "",
        ]
        for cat, items in sorted(categories.items(), key=lambda x: -len(x[1])):
            lines.append(f"- **{cat}**: {len(items)} artifact(s)")
        lines.append("")
        lines.append(
            f"Models used: {', '.join(sorted(set(a.get('model', '') for a in artifacts)))}"
        )
        return "\n".join(lines)

    def to_markdown(self, briefing: dict[str, Any]) -> str:
        """Render a briefing dict as formatted markdown."""
        lines = [
            f"🌅 **Morning Briefing — {briefing.get('date', 'Unknown')}**",
            "=" * 50,
            "",
            f"👤 **For:** {briefing.get('recipient', 'Operator')}",
            f"🕐 **Generated:** {briefing.get('generated_at', '')}",
            "",
        ]

        if briefing.get("error"):
            lines.append(f"⚠️ {briefing['error']}")
            return "\n".join(lines)

        # Stats
        lines.extend([
            "## 📊 Overnight Summary",
            f"- **Artifacts:** {len(briefing.get('artifacts', []))}",
            f"- **Models:** {', '.join(briefing.get('models', []))}",
            f"- **Tokens generated:** {briefing.get('total_tokens', 0):,}",
            f"- **GPU time:** {briefing.get('stats', {}).get('hours', 0)} hours",
            f"- **Cost:** $0.00 (all local)",
            "",
        ])

        # Executive summary
        if briefing.get("summary"):
            lines.extend(["## 📋 Executive Summary", "", briefing["summary"], ""])

        # Priority items
        priority_items = briefing.get("priority_items", [])
        if priority_items:
            lines.append("## 🔥 Priority Items")
            for item in priority_items[:10]:
                priority = item.get("priority", "low")
                icon = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(
                    priority, "⚪"
                )
                lines.append(
                    f"- {icon} **[{priority.upper()}]** {item.get('job_name', '?')} "
                    f"— {item.get('preview', '')[:120]}"
                )
            lines.append("")

        # Artifacts by category
        categories = briefing.get("categories", {})
        if categories:
            lines.append("## 📦 Artifacts by Category")
            for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
                lines.append(f"- **{cat}**: {count}")
            lines.append("")

        # All artifacts table
        lines.extend(["## 📑 All Artifacts", ""])
        for a in briefing.get("artifacts", []):
            lines.append(
                f"### {a.get('job_name', '?')} "
                f"`{a.get('job_type', '?')}` `{a.get('model', '?')}`"
            )
            lines.append(f"- Tokens: {a.get('tokens_generated', 0):,}")
            lines.append(f"- Time: {a.get('elapsed_seconds', 0):.1f}s")
            lines.append(f"- Priority: {a.get('priority', 'low')}")
            preview = a.get("preview", "")
            if preview:
                lines.append(f"\n> {preview[:200]}...")
            lines.append("")

        # Recommendations
        recs = briefing.get("recommendations", [])
        if recs:
            lines.append("## 🎯 Recommendations")
            for i, rec in enumerate(recs, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        # Confidence
        confidence = briefing.get("confidence_pct", 0)
        lines.append("---")
        lines.append(f"📐 **Confidence:** {confidence}% · {len(briefing.get('artifacts', []))} artifacts analyzed")

        return "\n".join(lines)

    def to_html(self, briefing: dict[str, Any]) -> str:
        """Render a briefing dict as a styled HTML page."""
        template = Template(HTML_TEMPLATE)
        return template.render(**briefing)

    def save_briefing(
        self,
        briefing: dict[str, Any],
        output_dir: str | Path | None = None,
        formats: list[str] | None = None,
    ) -> list[Path]:
        """
        Save the briefing in specified format(s).

        Args:
            briefing: The briefing data dict.
            output_dir: Where to save (defaults to the forge output dir).
            formats: List of formats: ['md', 'html']

        Returns:
            List of saved file paths.
        """
        out = Path(output_dir) if output_dir else self.output_dir
        out.mkdir(parents=True, exist_ok=True)
        date = briefing.get("date", datetime.now().strftime("%Y-%m-%d"))
        formats = formats or ["md"]
        paths: list[Path] = []

        if "md" in formats:
            md_path = out / f"briefing-{date}.md"
            md_path.write_text(self.to_markdown(briefing))
            paths.append(md_path)

        if "html" in formats:
            html_path = out / f"briefing-{date}.html"
            html_path.write_text(self.to_html(briefing))
            paths.append(html_path)

        return paths


